version: '3.5'
services:
  product:
    restart: on-failure
    image: j1cs/product
    ports:
      - '8080:8080'
    container_name: product
    environment:
      - MICRONAUT_ENVIRONMENTS=prod
      - JDBC_URL=jdbc:postgresql://postgres:5432/challenge
      - JDBC_DRIVER=org.postgresql.Driver
      - JDBC_USER=postgres
      - JDBC_PASSWORD=postgres123
      - REDIRECT_URL=http://localhost:8080/products
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: "postgres:alpine"
    container_name: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5      
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8000:8080"
